DecoratorLab/Models/Order/Order.cs
namespace DecoratorLab.Models
{
    public class Order
    {
        public string Beverage { get; set; }
        public string Condiments { get; set; }
        public decimal Total { get; set; }
    }
}

DecoratorLab/Controllers/OrderController.cs
using System.Web.Mvc;
using DecoratorLab.Models;
using System.Data.SqlClient;
namespace DecoratorLab.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitOrder(string beverageName, string[] condiments)
        {
            BeverageFactory aBeverageFactory = new BeverageFactory();
            BeverageStore aBeverageStore = new BeverageStore(aBeverageFactory);
            CondimentFactory aCondimentFactory = new CondimentFactory();
            CondimentStore aCondimentStore = new CondimentStore(aCondimentFactory);

            Beverage beverage = aBeverageStore.OrderBeverage(beverageName);
            beverage = aCondimentStore.OrderCondiments(beverage, condiments);
            string condimentString = "";
            int i = 0;
            if(condiments != null)
            {
                foreach (var condiment in condiments)
                {
                    if (i == 0)
                    {
                        condimentString = $"{condimentString}{condiment}";
                    }
                    else
                    {
                        condimentString = $"{condimentString}, {condiment}";
                    }
                    i++;
                }
            }
            

            Order order = new Order()
            {
                Beverage = beverageName,
                Condiments = condimentString,
                Total = beverage.Cost()
            };

            // Unsecure connection and should sanitize/parameterize but won't since it's a personal project.
            SqlConnection conn = new SqlConnection(@"Data Source=(localdb)\ProjectsV13;Initial Catalog=CoffeeDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");

            SqlCommand query = new SqlCommand();
            query = conn.CreateCommand();
            query.CommandText = $"INSERT INTO Orders(Beverage, Condiments, Total) VALUES('{order.Beverage}', '{order.Condiments}', '{order.Total}');";
            conn.Open();
            query.ExecuteNonQuery();
            conn.Close();
            ViewBag.Description = beverage.GetDescription();
            ViewBag.Cost = beverage.Cost();
            
            return View();
        }
    }
}

DecoratorLab/Views/Order/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2 class="center">Alfredbucks Order Form</h2>
<form action="@Url.Action("SubmitOrder", "Order")" method="post">
    <h4 class="center">Pick a Beverage</h4>
    <p>
        <input name="beverageName" type="radio" id="frenchRoast" value="French Roast"/>
        <label for="frenchRoast">French Roast ($1.00)</label>
    </p>
    <p>
        <input name="beverageName" type="radio" id="viennaRoast" value="Vienna Roast"/>
        <label for="viennaRoast">Vienna Roast ($1.20)</label>
    </p>
    <p>
        <input name="beverageName" type="radio" id="italianRoast" value="Italian Roast"/>
        <label for="italianRoast">Italian Roast ($1.00)</label>
    </p>
    <p>
        <input name="beverageName" type="radio" id="houseBlend" value="House Blend"/>
        <label for="houseBlend">House Blend ($1.00)</label>
    </p>
    <p>
        <input name="beverageName" type="radio" id="decaf" value="Decaf"/>
        <label for="decaf">Decaf ($1.00)</label>
    </p>
    <h4 class="center">Pick your Condiments</h4>
    <div class="row">
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="cream" name="condiments" value="Cream"/>
                <label for="cream">Cream ($1.00)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="skim" name="condiments" value="Skim"/>
                <label for="skim">Skim ($1.00)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="mocha" name="condiments" value="Mocha"/>
                <label for="mocha">Mocha ($0.75)</label>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="chocolate" name="condiments" value="Chocolate"/>
                <label for="chocolate">Chocolate ($0.50)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="vanilla" name="condiments" value="Vanilla"/>
                <label for="vanilla">Vanilla ($1.50)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="latte" name="condiments" value="Latte"/>
                <label for="latte">Latte ($2.00)</label>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="orangezest" name="condiments" value="Orange Zest"/>
                <label for="orangezest">Orange Zest ($0.50)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="ice" name="condiments" value="Ice"/>
                <label for="ice">Ice ($0.30)</label>
            </p>
        </div>
        <div class="col s12 m4">
            <p>
                <input type="checkbox" id="pumpkinSpice" name="condiments" value="Pumpkin Spice"/>
                <label for="pumpkinSpice">Pumpkin Spice ($1.00)</label>
            </p>
        </div>
    </div>
    <input type="submit" class="btn indigo darken-1" value="Submit Order" />
</form>

DecoratorLab/Views/Order/SubmitOrder.cshtml
@{
    ViewBag.Title = "Order Confirmation";
}

<h2>Order Confirmation</h2>
<h3>Cost: $@ViewBag.Cost</h3>
<h4>Description: @ViewBag.Description</h4>
<a href="@Url.Action("Index", "Order")">
    <button class="btn indigo darken-1">GO BACK</button>
</a>